### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by thucz** [dmar-bonn/active-gs#1]
Hi! Great work! When do you plan to release the code? I want to conduct my research based on your work

**Comment by liren-jin** [comment]
Since the paper is now under review, I will release my code around February 2025.

**Comment by thucz** [comment]
Thanks!

**Comment by vishxlyadav** [comment]
Thanks for the great work, Waiting for the code release.

**Comment by liren-jin** [comment]
Hi, thanks!
The paper is still under review at this moment.
I try my best to realse the code next week, but otherwise should be no later than the first week in March.
Stay tuned!
